apiVersion: sources.knative.dev/v1alpha1
kind: CamelSource
metadata:
  name: hello-world
spec:
  source:
    flow:
      from:
        uri: "timer:tick?period=10s"
        steps:
          - set-body:
              constant: Hello World!!
          - set-header:
              name: ce-type
              constant: hello.world
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
