apiVersion: sources.knative.dev/v1alpha1
kind: CamelSource
metadata:
  name: webhook
spec:
  source:
    flow:
      from:
        uri: "undertow:http://0.0.0.0:8080/abcde12345"
        steps:
          - set-body:
              constant: WEBHOOK
          - set-header:
              name: ce-type
              constant: webhook
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
