apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: dumper
